version: '3.2'
services:
  spotlyt: 
    build: .
    ports:
      - "5000"
    volumes:
      - type: bind
        source: ~/indexes/demo1 
        target: /index
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - type: bind
        source: ~/
        target: /etc/nginx
    depends_on:
      - spotlyt
    ports:
      - "80:80"
      - "443:443"
