version: '3'
services:
  spotlyt: 
    build: .
    ports:
      - "5000"
    volumes:
      - type: bind
        source: ~/index/demo1
        target: /index
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spotlyt
    ports:
      - "80:80"
